### ISSUE TITLE
Cannot build on MacOS

### ISSUE THREAD

**Issue by amelnikoff** [karolbe/repoint-r#1]
When I ran **mvn clean install** build is failing in module Repoint DFC Bundle
with 
`[ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:0.23.1:package-plugin (default-package-plugin) on project com.documentum.dfc: /Users/alexey/Projects/Tops/repoint-r/com.documentum.dfc/build.properties: bin.includes value(s) [lib/*] do not match any files. -> [Help 1]`

When I added lib folder to module with DFC jars build stopped failing there.

Now it failing with a lot of javac errors in Repoint eclipse plugin:

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.23.1:compile (default-compile) on project com.documentum.devprog.eclipsePlugin: Compilation failure: Compilation failure:
[ERROR] /Users/alexey/Projects/Tops/repoint-r/com.documentum.devprog/src/com/documentum/devprog/eclipse/libraryfunc/ViewAction.java:[39]
[ERROR] import com.documentum.fc.common.DfLogger;
[ERROR] ^^^^^^^^^^^^^^^^^
etc.
```

Any suggestions how to solve it?

**Comment by karolbe** [comment]
Hi

You will need DFC libraries and dependencies in repoint-r/com.documentum.dfc/lib, this is what I have there:

bash-3.2$ cd lib/
bash-3.2$ ls
All-MB.jar      bpmutil.jar     commons-codec-1.3.jar   dfc.jar         jcifs-krb5-1.3.1.jar    log4j.properties    vsj-standard-3.3.jar    xtrim-server.jar
DDS.jar         build.properties    commons-lang-2.4.jar    dfcbase.jar     jsafeFIPS.jar       messageArchive.jar  workflow.jar
DmcRecords.jar      certjFIPS.jar       config.jar      dms-client-api.jar  jsr173_api.jar      messageService.jar  xalan.jar
activation.jar      ci.jar          configservice-api.jar   jaxb-api.jar        krbutil.jar     subscription.jar    xercesImpl.jar
aspectjrt.jar       collaboration.jar   configservice-impl.jar  jaxb-impl.jar       log4j.jar       vsj-license.jar     xtrim-api.jar

**Comment by amelnikoff** [comment]
Sorry for not answering.
I finished my work with Documentum )

You wrote the same thing what I've done before and tried again. No luck. The same result, compiler doesn't load classpath:

> [ERROR] IDfEnumeration cannot be resolved to a type
> [ERROR] /Users/alexey/Projects/tmp/repoint-r/com.documentum.devprog/src/com/documentum/devprog/eclipse/bof/BOF53Helper.java:[128]
> [ERROR] DfLogger.error(logId, "Global Module Registry is not Accessible: "
> [ERROR] ^^^^^^^^
> [ERROR] DfLogger cannot be resolved
> [ERROR] 2386 problems (2386 errors)
> [ERROR] -> [Help 1]

I forgot to say, that I tried to build master branch.

Closing issue because I don't have enough time to check that problem.
